package org.firstinspires.ftc.teamcode.decode.helper;

public interface Constants {

    boolean PICK_BALLS_LINE_1_FLAG = true;
    boolean PICK_BALLS_LINE_2_FLAG = true;
    boolean PICK_BALLS_LINE_3_FLAG = true;

    boolean PICK_FROM_HUMAN_AREA_FLAG_1 = true;
    boolean PICK_FROM_HUMAN_AREA_FLAG_2 = true;
    boolean PICK_FROM_HUMAN_AREA_FLAG_3 = true;

    boolean RELEASE_FLAG = true;

    double SPEED_CONTROL_FACTOR = 1;

    int DEFAULT_SHOOTER_VELOCITY_POSITION_1 = 1400;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_2 = 1100;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_3 = 960;

    int DEFAULT_SHOOTER_VELOCITY_POSITION_1_AUTON = 1400;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_2_AUTON = 1140;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_3_AUTON = 960;

    int LINE_1_INTAKE_WAIT_TIME = 600;
    int LINE_2_INTAKE_WAIT_TIME = 640;
    int LINE_3_INTAKE_WAIT_TIME = 640;

    int HUMAN_AREA_INTAKE_WAIT_TIME = 1000;

    int CHANGE_SHOOTER_VELOCITY_BY = 50;

    double DEFAULT_OUTPUT_ANGLE_POSITION_1 = 0.52;
    double DEFAULT_OUTPUT_ANGLE_POSITION_2 = 0.47;
    double DEFAULT_OUTPUT_ANGLE_POSITION_3 = 0.435;

    double DEFAULT_OUTPUT_ANGLE_POSITION_1_AUTON = 0.52;
    double DEFAULT_OUTPUT_ANGLE_POSITION_2_AUTON = 0.47;
    double DEFAULT_OUTPUT_ANGLE_POSITION_3_AUTON = 0.435;

    double SERVO_HOME_POSITION = 0.5;
    double KICKER_SERVO_HOME_POSITION = 0.025;

    String BLUE_LAUNCH_LOCATION_1 = "BlueLocation1";
    String BLUE_LAUNCH_LOCATION_2 = "BlueLocation2";
    String BLUE_LAUNCH_LOCATION_3 = "BlueLocation3";
    String RED_LAUNCH_LOCATION_1 = "RedLocation1";
    String RED_LAUNCH_LOCATION_2 = "RedLocation2";
    String RED_LAUNCH_LOCATION_3 = "RedLocation3";

    String RED_LAUNCH_LOCATION_1_AUTON = "RedLocation1Auton";
    String RED_LAUNCH_LOCATION_2_AUTON = "RedLocation2Auton";
    String RED_LAUNCH_LOCATION_3_AUTON = "RedLocation3Auton";

    double TELEOP_DEFAULT_SPEED = 1.0;
}
