package org.firstinspires.ftc.teamcode.decode.helper;

public interface Constants {

    double SPEED_CONTROL_FACTOR = 0.25;

    int DEFAULT_SHOOTER_VELOCITY_POSITION_1 = 1600;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_2 = 1240;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_3 = 1140;

//    int DEFAULT_SHOOTER_VELOCITY_POSITION_1_AUTON = 1600;
    int DEFAULT_SHOOTER_VELOCITY_POSITION_2_AUTON = 1240;
//    int DEFAULT_SHOOTER_VELOCITY_POSITION_3_AUTON = 1180;

    int CHANGE_SHOOTER_VELOCITY_BY = 50;

    double DEFAULT_OUTPUT_ANGLE_POSITION_1 = 0.51;
    double DEFAULT_OUTPUT_ANGLE_POSITION_2 = 0.48;
    double DEFAULT_OUTPUT_ANGLE_POSITION_3 = 0.44;

//    double DEFAULT_OUTPUT_ANGLE_POSITION_1_AUTON = 0.51;
    double DEFAULT_OUTPUT_ANGLE_POSITION_2_AUTON = 0.48;
//    double DEFAULT_OUTPUT_ANGLE_POSITION_3_AUTON = 0.44;

    double SERVO_HOME_POSITION = 0.5;
    double KICKER_SERVO_HOME_POSITION = 0.025;

    String BLUE_LAUNCH_LOCATION_1 = "BlueLocation1";
    String BLUE_LAUNCH_LOCATION_2 = "BlueLocation2";
    String BLUE_LAUNCH_LOCATION_3 = "BlueLocation3";
    String RED_LAUNCH_LOCATION_1 = "RedLocation1";
    String RED_LAUNCH_LOCATION_2 = "RedLocation2";
    String RED_LAUNCH_LOCATION_3 = "RedLocation3";

    String RED_LAUNCH_LOCATION_2_AUTON = "RedLocation2Auton";

    double TELEOP_DEFAULT_SPEED = 1.0;
}
